export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_RESPONSE = "GET_RESPONSE";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const PROFILE_POST_ADDED = "PROFILE_POST_ADDED";
export const FEED_POST_ADDED = "FEED_POST_ADDED";
export const CREATION_POST_ERROR = "CREATION_POST_ERROR";

export const IMAGE_SAVED = "IMAGE_SAVED";
export const SAVE_IMAGE_ERROR = "SAVE_IMAGE_ERROR";

export const GET_FEED_LOADING = "GET_FEED_LOADING";
export const GET_FEED_LOADED = "GET_FEED_LOADED";
export const GET_FEED_ERROR = "GET_FEED_ERROR";

export const GET_PROFILE_POSTS_LOADING = "GET_PROFILE_POSTS_LOADING";
export const GET_PROFILE_POSTS_LOADED = "GET_PROFILE_POSTS_LOADED";
export const GET_PROFILE_POSTS_ERROR = "GET_PROFILE_POSTS_ERROR";

export const FEED_ADDED = "FEED_ADDED";

export const PROFILE_POST_LIKED = "PROFILE_POST_LIKED";
export const PROFILE_POST_UNLIKED = "PROFILE_POST_UNLIKED";
export const FEED_POST_LIKED = "FEED_POST_LIKED";
export const FEED_POST_UNLIKED = "FEED_POST_UNLIKED";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const UNLIKE_POST_ERROR = "UNLIKE_POST_ERROR";

export const FEED_COMMENT_ADDED = "FEED_COMMENT_ADDED";
export const PROFILE_COMMENT_ADDED = "PROFILE_COMMENT_ADDED";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const FOLLOWING_ADDED = "FOLLOWING_ADDED";
export const FOLLOWING_REMOVED = "FOLLOWING_REMOVED";
export const FOLLOWING_ERROR = "FOLLOWING_ERROR";

export const USER_NAME_CHANGED = "USER_NAME_CHANGED";
export const CHANGE_USER_NAME_ERROR = "CHANGE_USER_NAME_ERROR";

export const USER_INFO_CHANGED = "USER_INFO_CHANGED";
export const CHANGE_USER_INFO_ERROR = "CHANGE_USER_INFO_ERROR";

export const PROFILE_PICTURE_CHANGED = "PROFILE_PICTURE_CHANGED";
export const CHANGE_PROFILE_PICTURE_ERROR = "CHANGE_PROFILE_PICTURE_ERROR";
export const OLD_PROFILE_PICTURE_DELETED = "OLD_PROFILE_PICTURE_DELETED";
export const DELETE_OLD_PROFILE_PICTURE_ERROR = "DELETE_OLD_PROFILE_PICTURE_ERROR";

export const COVER_PICTURE_CHANGED = "COVER_PICTURE_CHANGED";
export const CHANGE_COVER_PICTURE_ERROR = "CHANGE_COVER_PICTURE_ERROR";
export const OLD_COVER_PICTURE_DELETED = "OLD_COVER_PICTURE_DELETED";
export const DELETE_OLD_COVER_PICTURE_ERROR = "DELETE_OLD_COVER_PICTURE_ERROR";

export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECKING_EMAIL_ERROR = "CHECKING_EMAIL_ERROR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const GET_FILTERED_FEED = "GET_FILTERED_FEED";
export const FILTERING_FEED_ERROR = "FILTERING_FEED_ERROR";

export const GET_FILTERED_PROFILE_POSTS = "GET_FILTERED_PROFILE_POSTS";
export const FILTERING_PROFILE_POSTS_ERROR = "FILTERING_PROFILE_POSTS_ERROR";