export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_RESPONSE = "GET_RESPONSE";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const GET_POSTS_LOADING = "GET_POSTS_LOADING";
export const GET_POSTS_LOADED = "GET_POSTS_LOADED";

export const PROFILE_POST_ADDED = "PROFILE_POST_ADDED";
export const FEED_POST_ADDED = "FEED_POST_ADDED";
export const CREATION_POST_ERROR = "CREATION_POST_ERROR";

export const IMAGE_SAVED = "IMAGE_SAVED";
export const SAVE_IMAGE_ERROR = "SAVE_IMAGE_ERROR";

export const GET_FEED_LOADING = "GET_FEED_LOADING";
export const GET_FEED_LOADED = "GET_FEED_LOADED";
export const GET_FEED_ERROR = "GET_FEED_ERROR";

export const FEED_ADDED = "FEED_ADDED";

export const PROFILE_POST_LIKED = "PROFILE_POST_LIKED";
export const PROFILE_POST_UNLIKED = "PROFILE_POST_UNLIKED";
export const FEED_POST_LIKED = "FEED_POST_LIKED";
export const FEED_POST_UNLIKED = "FEED_POST_UNLIKED";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const UNLIKE_POST_ERROR = "UNLIKE_POST_ERROR";

export const FEED_COMMENT_ADDED = "FEED_COMMENT_ADDED";
export const PROFILE_COMMENT_ADDED = "PROFILE_COMMENT_ADDED";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";
